In [1]:
import pandas as pd

In [2]:
df_ber = pd.read_csv("../data/derived/kita_data_ber.csv", index_col=[0])

In [3]:
df_ber.head(100)

,kita_name,kita_address,kita_spots
0,paul kirschkern,"10115 Berlin, Anklamerstr. 29",25
1,kinderinsel e. v. inselnest,"10115 Berlin, Eichendorffstraße 17",25
2,kinderladen 'piraterie',"10115 Berlin, Anklamer Str. 22",20
3,berlin cosmopolitan school - kindergarten in t...,"10115 Berlin, Invalidenstrasse 130",248
4,ina.kinder.garten habersaathstraße,"10115 Berlin, Habersaathstraße 5",90
...,...,...,...
95,evangelische kita sonnenblume,"10245 Berlin, Niemannstraße 1",100
96,ktp spreemücken,"10245 Berlin, Stralauer Allee 17c",10
97,kita krikelkrake,"10245 Berlin, Dannecker Straße 8",15
98,kila friedrichsklain,"10247 Berlin, Oderstraße 34",25
99,frÖbel-kindergarten „kleiner muck“,"10247 Berlin, Rigaer Straße 53",115

In [4]:
kita_list = list(df_ber.kita_address)

In [5]:
plz = [x[:5] for x in kita_list]

df_ber["plz"] = plz

In [6]:
df_ber

,kita_name,kita_address,kita_spots,plz
0,paul kirschkern,"10115 Berlin, Anklamerstr. 29",25,10115
1,kinderinsel e. v. inselnest,"10115 Berlin, Eichendorffstraße 17",25,10115
2,kinderladen 'piraterie',"10115 Berlin, Anklamer Str. 22",20,10115
3,berlin cosmopolitan school - kindergarten in t...,"10115 Berlin, Invalidenstrasse 130",248,10115
4,ina.kinder.garten habersaathstraße,"10115 Berlin, Habersaathstraße 5",90,10115
...,...,...,...,...
1934,spreepferdchen - waldorforientierte kita,"14199 Berlin, Cunostr. 1",40,14199
1935,kindertagespflege andrea fuchs,"14199 Berlin, Akazienallee 34",20,14199
1936,ekt pünktchen und anton ev.,"14199 Berlin, hohenzollerndamm 130",16,14199
1937,kinderladen akazienhof e.v.,"14199 Berlin, Weinheimer Str.11",18,14199
1938,ekg (orgelpfeifen) kreuzkirche,"14199 Berlin, Kirchstr. 15/16",47,14199

In [7]:
df_ber.loc[df_ber['plz'] == "13187"]

,kita_name,kita_address,kita_spots,plz
1460,kita der ev. kirchengem. alt-pankow,"13187 Berlin, Breite Str. 038",30,13187
1461,ekt auenland e.v.,"13187 Berlin, Brehmestraße 60",19,13187
1462,kinderladen spilemäuse,"13187 Berlin, Wolfshagenerstr.81",25,13187
1463,kinderladen ratzefatze e.v,"13187 Berlin, Florapromenade 1",19,13187
1464,kindergarten montessori-haus pestalozzistraße,"13187 Berlin, Pestalozzistr. 9-11",160,13187
1465,kindergarten die kleinen strolche,"13187 Berlin, Neue Schönholzer Str. 25",80,13187
1466,katholische kita st. georg,"13187 Berlin, Breite Str. 44",65,13187
1467,kita am brennerberg,"13187 Berlin, Tiroler Straße 29",135,13187
1468,kita der ev. kirchengem. martin-luther,"13187 Berlin, Pradelstr. 011",74,13187
1469,kindertagesstätte clownfisch,"13187 Berlin, Maximilianstr. 6",22,13187
1470,kita 'kleine leute ganz groß',"13187 Berlin, Florastraße 68",20,13187
1471,kita zipfelmütze,"13187 Berlin, Görschstraße 15",110,13187
1472,kita blumenkinder,"13187 Berlin, Florastr. 23",23,13187
1473,gartenkinder e.v.,"13187 Berlin, Neumannstraße 73",25,13187
1474,kleine florakinder,"13187 Berlin, Görschstr. 40",10,13187
1475,kita vesaliusstraße,"13187 Berlin, Vesaliusstr. 068",190,13187
1476,montessori kinderhaus sternenwiese,"13187 Berlin, Berliner Str. 128",60,13187
1477,lara kita,"13187 Berlin, Schulstraße 30",139,13187
1478,kita 'pankower wichtel' der jao ggmbh,"13187 Berlin, Dusekestr. 14-22",130,13187
1479,kita 'villa sternenschiff',"13187 Berlin, Benjamin-Vogelsdorff-Str. 3",45,13187
1480,kindergarten 'affenbande',"13187 Berlin, Mendelstraße 42",30,13187
1481,kita 'mondschaukel',"13187 Berlin, Gaillardstraße 1",20,13187
1482,kita sonnenblume2,"13187 Berlin, Schönholzer Str. 4d",80,13187
1483,ekt simsalabim e.v,"13187 Berlin, Wilhelm - Kuhr Straße 83",16,13187
1484,pankekinder e.v.,"13187 Berlin, Wollankstr.119",53,13187
1485,kindergarten schlossparkspatzen,"13187 Berlin, Mendelstr. 49-51","integration, musiklalische früherziehung",13187
1486,kinderladen garuda e.v.,"13187 Berlin, Kreuzstraße 5",20,13187
1487,stadtkinder pankow e. v.,"13187 Berlin, Rettigweg 4",18,13187
1488,verbundkita pankow,"13187 Berlin, Wolfshagener Str. 68",15,13187
1489,kinderladen krikelkrakel,"13187 Berlin, Breite Str. 7",22,13187
1490,platanus kindergarten,"13187 Berlin, Berliner Straße 12",0,13187
1491,kinderland ferdinand,"13187 Berlin, Brehmestraße 35",25,13187
1492,freche fledermäuse - pankow,"13187 Berlin, Schönholzer Str. 2",18,13187
1493,kita toblacher,"13187 Berlin, Toblacher Straße 42, Eingang Tir...",35,13187
1494,junior 1 kita am bürgerpark,"13187 Berlin, Parkstraße 1",25,13187
1495,kita 'piwi',"13187 Berlin, Wollankstraße 11",35,13187
1496,ekt glückskind,"13187 Berlin, Görschstraße 11",26,13187

In [8]:
import numpy as np

df_ber["kita_spots"] = np.where(df_ber["kita_spots"].str.isdigit(), df_ber["kita_spots"], 0)
df_ber["plz"] = np.where(df_ber["plz"].str.isdigit(), df_ber["plz"], 0)

In [9]:
df_ber["kita_spots"] = df_ber["kita_spots"].astype(int)
df_ber["plz"] = df_ber["plz"].astype(int)

In [10]:
df_ber.to_csv(r'../data/derived/kita_data_berlin_clean.csv')
df_ber.to_json(r'../data/derived/kita_data_berlin_clean.json')

In [11]:
df_ber

,kita_name,kita_address,kita_spots,plz
0,paul kirschkern,"10115 Berlin, Anklamerstr. 29",25,10115
1,kinderinsel e. v. inselnest,"10115 Berlin, Eichendorffstraße 17",25,10115
2,kinderladen 'piraterie',"10115 Berlin, Anklamer Str. 22",20,10115
3,berlin cosmopolitan school - kindergarten in t...,"10115 Berlin, Invalidenstrasse 130",248,10115
4,ina.kinder.garten habersaathstraße,"10115 Berlin, Habersaathstraße 5",90,10115
...,...,...,...,...
1934,spreepferdchen - waldorforientierte kita,"14199 Berlin, Cunostr. 1",40,14199
1935,kindertagespflege andrea fuchs,"14199 Berlin, Akazienallee 34",20,14199
1936,ekt pünktchen und anton ev.,"14199 Berlin, hohenzollerndamm 130",16,14199
1937,kinderladen akazienhof e.v.,"14199 Berlin, Weinheimer Str.11",18,14199
1938,ekg (orgelpfeifen) kreuzkirche,"14199 Berlin, Kirchstr. 15/16",47,14199

In [12]:
#from geopy.geocoders import Nominatim
#geolocator = Nominatim(user_agent="test2")

#from geopy.extra.rate_limiter import RateLimiter
#geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)
#df_ber['geo_address'] = df_ber(df_ber['plz']=="10559").apply(geocode)

In [13]:
#df_ber = df_ber.dropna()
#df_ber["plz"] = df_ber["plz"].astype(float)

In [14]:
import numpy as np

In [15]:
df_ber.dtypes

kita_name       object
kita_address    object
kita_spots       int32
plz              int32
dtype: object